'use strict';

module.exports = function createButlerBridge(ipcRenderer) {
  return {
    butler: {
      scanApps: () => ipcRenderer.invoke('butler:scan-apps'),
      openApp: (name) => ipcRenderer.invoke('butler:open-app', name),
      findFiles: (query, category, maxResults) => ipcRenderer.invoke('butler:find-files', { query, category, maxResults }),
      findExeInFolder: (folderPath, appName) => ipcRenderer.invoke('butler:find-exe-in-folder', { folderPath, appName }),
      createFile: (name, content) => ipcRenderer.invoke('butler:create-file', { name, content }),
      createDoc: (name, content) => ipcRenderer.invoke('butler:create-doc', { name, content }),
      openFolder: (pathValue) => ipcRenderer.invoke('butler:open-folder', pathValue),
      openFile: (pathValue) => ipcRenderer.invoke('butler:open-file', pathValue),
      emptyTrash: () => ipcRenderer.invoke('butler:empty-trash'),
      lockScreen: () => ipcRenderer.invoke('butler:lock-screen'),
      shutdown: () => ipcRenderer.invoke('butler:shutdown'),
      restart: () => ipcRenderer.invoke('butler:restart'),
      screenshot: () => ipcRenderer.invoke('butler:screenshot'),

      copy: (src, dest) => ipcRenderer.invoke('butler:copy', { src, dest }),
      move: (src, dest) => ipcRenderer.invoke('butler:move', { src, dest }),
      delete: (item, permanent) => ipcRenderer.invoke('butler:delete', { item, permanent }),
      rename: (oldPath, newPath) => ipcRenderer.invoke('butler:rename', { oldPath, newPath }),
      createFolder: (folderPath) => ipcRenderer.invoke('butler:create-folder', { folderPath }),
      listDir: (dirPath) => ipcRenderer.invoke('butler:list-dir', { dirPath }),
      fileInfo: (filePath) => ipcRenderer.invoke('butler:file-info', { filePath }),

      listProcesses: () => ipcRenderer.invoke('butler:list-processes'),
      killByName: (name) => ipcRenderer.invoke('butler:kill-by-name', { name }),
      sysInfo: () => ipcRenderer.invoke('butler:sys-info'),
      battery: () => ipcRenderer.invoke('butler:battery'),
      diskUsage: (drivePath) => ipcRenderer.invoke('butler:disk-usage', { drivePath }),

      getClipboard: () => ipcRenderer.invoke('butler:get-clipboard'),
      setClipboard: (text) => ipcRenderer.invoke('butler:set-clipboard', { text }),
      clearClipboard: () => ipcRenderer.invoke('butler:clear-clipboard'),

      setVolume: (level) => ipcRenderer.invoke('butler:set-volume', { level }),
      mute: (mute) => ipcRenderer.invoke('butler:mute', { mute }),
      getVolume: () => ipcRenderer.invoke('butler:get-volume'),

      getIp: () => ipcRenderer.invoke('butler:get-ip'),
      ping: (host) => ipcRenderer.invoke('butler:ping', { host }),
      flushDns: () => ipcRenderer.invoke('butler:flush-dns'),
      listWifi: () => ipcRenderer.invoke('butler:list-wifi'),

      getEnv: (variable) => ipcRenderer.invoke('butler:get-env', { variable }),
      setEnv: (variable, value) => ipcRenderer.invoke('butler:set-env', { variable, value }),

      cleanTemp: () => ipcRenderer.invoke('butler:clean-temp'),
      weather: (city) => ipcRenderer.invoke('butler:weather', { city }),
      qrCode: (text) => ipcRenderer.invoke('butler:qr-code', { text }),
      speedTest: () => ipcRenderer.invoke('butler:speed-test'),
      morningDigest: () => ipcRenderer.invoke('butler:morning-digest'),
      define: (word) => ipcRenderer.invoke('butler:define', { word }),
      translate: (text, from, to) => ipcRenderer.invoke('butler:translate', { text, from, to }),
      sendEmail: (to, subject, body) => ipcRenderer.invoke('butler:send-email', { to, subject, body }),
      downloadMedia: (url, format) => ipcRenderer.invoke('butler:download-media', { url, format }),
      setWallpaper: (imagePath) => ipcRenderer.invoke('butler:set-wallpaper', { imagePath }),

      runPs: (script) => ipcRenderer.invoke('butler:run-ps', { script }),
      runCmd: (command) => ipcRenderer.invoke('butler:run-cmd', { command }),
      logoff: () => ipcRenderer.invoke('butler:logoff'),

      getSteamGames: () => ipcRenderer.invoke('butler:get-steam-games'),
      getEpicGames: () => ipcRenderer.invoke('butler:get-epic-games'),
      launchGame: (gameName) => ipcRenderer.invoke('butler:launch-game', { gameName }),

      zip: (src, out) => ipcRenderer.invoke('butler:zip', { source: src, output: out }),
      unzip: (zipPath, dest) => ipcRenderer.invoke('butler:unzip', { zipPath, dest }),
      run: (cmd, args) => ipcRenderer.invoke('butler:run', { cmd, args }),
      runAsAdmin: (cmd) => ipcRenderer.invoke('butler:run-as-admin', { cmd }),
      listWindows: () => ipcRenderer.invoke('butler:list-windows'),
      windowAction: (action, title) => ipcRenderer.invoke('butler:window-action', { action, title }),
      sendKeys: (keys) => ipcRenderer.invoke('butler:send-keys', { keys }),
      mouseMove: (x, y) => ipcRenderer.invoke('butler:mouse-move', { x, y }),
      mouseClick: (button) => ipcRenderer.invoke('butler:mouse-click', { button }),
      pasteClipboard: () => ipcRenderer.invoke('butler:paste-clipboard'),
      getClipboardImg: () => ipcRenderer.invoke('butler:get-clipboard-img'),
      connectWifi: (ssid, password) => ipcRenderer.invoke('butler:connect-wifi', { ssid, password }),
      netAdapter: (adapter, action) => ipcRenderer.invoke('butler:net-adapter', { adapter, action }),
      sleep: (seconds) => ipcRenderer.invoke('butler:sleep', { seconds }),
      scheduleOnce: (time, command) => ipcRenderer.invoke('butler:schedule-once', { time, command }),
      cancelTask: (taskName) => ipcRenderer.invoke('butler:cancel-task', { taskName }),
      startup: (action, cmd, name) => ipcRenderer.invoke('butler:startup', { action, cmd, name }),
      regRead: (hive, key, value) => ipcRenderer.invoke('butler:reg-read', { hive, key, value }),
      regWrite: (hive, key, value, data, type) => ipcRenderer.invoke('butler:reg-write', { hive, key, value, data, type }),
      listSoftware: () => ipcRenderer.invoke('butler:list-software'),
      uninstall: (name) => ipcRenderer.invoke('butler:uninstall', { name }),
      checkUpdates: () => ipcRenderer.invoke('butler:check-updates'),
      installPkg: (name) => ipcRenderer.invoke('butler:install-pkg', { name }),
      ejectUsb: (letter) => ipcRenderer.invoke('butler:eject-usb', { letter }),
      runJs: (code) => ipcRenderer.invoke('butler:run-js', { code }),
      chkdsk: (drive) => ipcRenderer.invoke('butler:chkdsk', { drive }),

      deletePerm: (item) => ipcRenderer.invoke('butler:delete', { item, permanent: true }),
      killPid: (pid) => ipcRenderer.invoke('system:kill-process', pid),
      unmute: () => ipcRenderer.invoke('butler:mute', { mute: false }),
      findFile: (name, root) => ipcRenderer.invoke('butler:find-file', { name, root }),
      grepFile: (pattern, file) => ipcRenderer.invoke('butler:grep-file', { pattern, file }),
      runPython: (script) => ipcRenderer.invoke('butler:run-python', { script }),
      gitCommand: (cmd, repo) => ipcRenderer.invoke('butler:git', { cmd, repo }),
      dockerStatus: () => ipcRenderer.invoke('butler:docker-status'),
      notify: (title, message) => ipcRenderer.invoke('butler:notify', { title, message }),
      recordScreen: (action) => ipcRenderer.invoke('butler:record-screen', { action }),
    },
  };
};
